/**
 * Framework-specific Code Generator for Nano UI
 * Generates React, Vue, Svelte, and Vanilla components
 */

import { DesignTokens } from './tokens';

export type Framework = 'react' | 'vue' | 'svelte' | 'vanilla';

export interface ComponentSpec {
  name: string;
  description: string;
  variants: string[];
  props: Record<string, string>;
}

/**
 * Generate React component with design tokens
 */
function generateReactComponent(tokens: DesignTokens): string {
  return `/**
 * ${tokens.meta.name} - React Components
 * Generated by Nano UI
 */

import React from 'react';
import './variables.css';

// Button Component
export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'accent';
  size?: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
  onClick?: () => void;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  children,
  onClick,
}) => {
  const baseStyles = {
    fontFamily: 'var(--font-body)',
    fontWeight: 500,
    borderRadius: 'var(--radius-md)',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  };

  const variantStyles = {
    primary: {
      backgroundColor: 'var(--color-primary)',
      color: 'var(--color-background)',
    },
    secondary: {
      backgroundColor: 'var(--color-secondary)',
      color: 'var(--color-text)',
    },
    accent: {
      backgroundColor: 'var(--color-accent)',
      color: 'var(--color-background)',
    },
  };

  const sizeStyles = {
    sm: { padding: 'var(--spacing-2) var(--spacing-4)', fontSize: '14px' },
    md: { padding: 'var(--spacing-3) var(--spacing-6)', fontSize: '16px' },
    lg: { padding: 'var(--spacing-4) var(--spacing-8)', fontSize: '18px' },
  };

  return (
    <button
      style={{ ...baseStyles, ...variantStyles[variant], ...sizeStyles[size] }}
      onClick={onClick}
    >
      {children}
    </button>
  );
};

// Card Component
export interface CardProps {
  children: React.ReactNode;
  shadow?: 'sm' | 'md' | 'lg';
  padding?: 'sm' | 'md' | 'lg';
}

export const Card: React.FC<CardProps> = ({
  children,
  shadow = 'md',
  padding = 'md',
}) => {
  const paddingMap = {
    sm: 'var(--spacing-4)',
    md: 'var(--spacing-6)',
    lg: 'var(--spacing-8)',
  };

  return (
    <div
      style={{
        backgroundColor: 'var(--color-surface)',
        borderRadius: 'var(--radius-lg)',
        boxShadow: \`var(--shadow-\${shadow})\`,
        padding: paddingMap[padding],
      }}
    >
      {children}
    </div>
  );
};

// Heading Component
export interface HeadingProps {
  level?: 1 | 2 | 3 | 4 | 5 | 6;
  children: React.ReactNode;
}

export const Heading: React.FC<HeadingProps> = ({ level = 1, children }) => {
  const Tag = \`h\${level}\` as keyof JSX.IntrinsicElements;
  const sizes = {
    1: '48px',
    2: '36px',
    3: '28px',
    4: '24px',
    5: '20px',
    6: '16px',
  };

  return (
    <Tag
      style={{
        fontFamily: 'var(--font-display)',
        fontWeight: 700,
        color: 'var(--color-text)',
        fontSize: sizes[level],
        margin: 0,
      }}
    >
      {children}
    </Tag>
  );
};

// Text Component
export interface TextProps {
  size?: 'sm' | 'md' | 'lg';
  color?: 'primary' | 'secondary' | 'muted';
  children: React.ReactNode;
}

export const Text: React.FC<TextProps> = ({
  size = 'md',
  color = 'primary',
  children,
}) => {
  const sizeMap = { sm: '14px', md: '16px', lg: '18px' };
  const colorMap = {
    primary: 'var(--color-text)',
    secondary: 'var(--color-secondary)',
    muted: 'color-mix(in srgb, var(--color-text) 60%, transparent)',
  };

  return (
    <p
      style={{
        fontFamily: 'var(--font-body)',
        fontSize: sizeMap[size],
        color: colorMap[color],
        lineHeight: 1.6,
        margin: 0,
      }}
    >
      {children}
    </p>
  );
};
`;
}

/**
 * Generate Vue component
 */
function generateVueComponent(tokens: DesignTokens): string {
  return `<!--
  ${tokens.meta.name} - Vue Components
  Generated by Nano UI
-->

<template>
  <button
    :class="['btn', \`btn--\${variant}\`, \`btn--\${size}\`]"
    @click="$emit('click')"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
defineProps<{
  variant?: 'primary' | 'secondary' | 'accent';
  size?: 'sm' | 'md' | 'lg';
}>();

defineEmits<{
  click: [];
}>();
</script>

<style scoped>
@import './variables.css';

.btn {
  font-family: var(--font-body);
  font-weight: 500;
  border-radius: var(--radius-md);
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
}

.btn--primary {
  background-color: var(--color-primary);
  color: var(--color-background);
}

.btn--secondary {
  background-color: var(--color-secondary);
  color: var(--color-text);
}

.btn--accent {
  background-color: var(--color-accent);
  color: var(--color-background);
}

.btn--sm {
  padding: var(--spacing-2) var(--spacing-4);
  font-size: 14px;
}

.btn--md {
  padding: var(--spacing-3) var(--spacing-6);
  font-size: 16px;
}

.btn--lg {
  padding: var(--spacing-4) var(--spacing-8);
  font-size: 18px;
}
</style>
`;
}

/**
 * Generate Svelte component
 */
function generateSvelteComponent(tokens: DesignTokens): string {
  return `<!--
  ${tokens.meta.name} - Svelte Components
  Generated by Nano UI
-->

<script lang="ts">
  import './variables.css';

  export let variant: 'primary' | 'secondary' | 'accent' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
</script>

<button class="btn btn--{variant} btn--{size}" on:click>
  <slot />
</button>

<style>
  .btn {
    font-family: var(--font-body);
    font-weight: 500;
    border-radius: var(--radius-md);
    border: none;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .btn--primary {
    background-color: var(--color-primary);
    color: var(--color-background);
  }

  .btn--secondary {
    background-color: var(--color-secondary);
    color: var(--color-text);
  }

  .btn--accent {
    background-color: var(--color-accent);
    color: var(--color-background);
  }

  .btn--sm {
    padding: var(--spacing-2) var(--spacing-4);
    font-size: 14px;
  }

  .btn--md {
    padding: var(--spacing-3) var(--spacing-6);
    font-size: 16px;
  }

  .btn--lg {
    padding: var(--spacing-4) var(--spacing-8);
    font-size: 18px;
  }
</style>
`;
}

/**
 * Generate vanilla HTML/CSS
 */
function generateVanillaComponents(tokens: DesignTokens): string {
  return `/**
 * ${tokens.meta.name} - Vanilla CSS Components
 * Generated by Nano UI
 */

@import './variables.css';

/* Button */
.btn {
  font-family: var(--font-body);
  font-weight: 500;
  border-radius: var(--radius-md);
  border: none;
  cursor: pointer;
  transition: all 0.2s ease;
}

.btn:hover {
  filter: brightness(1.1);
}

.btn--primary {
  background-color: var(--color-primary);
  color: var(--color-background);
}

.btn--secondary {
  background-color: var(--color-secondary);
  color: var(--color-text);
}

.btn--accent {
  background-color: var(--color-accent);
  color: var(--color-background);
}

.btn--sm {
  padding: var(--spacing-2) var(--spacing-4);
  font-size: 14px;
}

.btn--md {
  padding: var(--spacing-3) var(--spacing-6);
  font-size: 16px;
}

.btn--lg {
  padding: var(--spacing-4) var(--spacing-8);
  font-size: 18px;
}

/* Card */
.card {
  background-color: var(--color-surface);
  border-radius: var(--radius-lg);
  padding: var(--spacing-6);
}

.card--shadow-sm { box-shadow: var(--shadow-sm); }
.card--shadow-md { box-shadow: var(--shadow-md); }
.card--shadow-lg { box-shadow: var(--shadow-lg); }

/* Heading */
.heading {
  font-family: var(--font-display);
  font-weight: 700;
  color: var(--color-text);
  margin: 0;
}

.heading--1 { font-size: 48px; }
.heading--2 { font-size: 36px; }
.heading--3 { font-size: 28px; }
.heading--4 { font-size: 24px; }
.heading--5 { font-size: 20px; }
.heading--6 { font-size: 16px; }

/* Text */
.text {
  font-family: var(--font-body);
  line-height: 1.6;
  margin: 0;
}

.text--sm { font-size: 14px; }
.text--md { font-size: 16px; }
.text--lg { font-size: 18px; }
`;
}

/**
 * Generate code for specified framework(s)
 */
export function generateCode(
  tokens: DesignTokens,
  framework: Framework | 'all'
): Record<string, string> {
  const generators: Record<Framework, () => string> = {
    react: () => generateReactComponent(tokens),
    vue: () => generateVueComponent(tokens),
    svelte: () => generateSvelteComponent(tokens),
    vanilla: () => generateVanillaComponents(tokens),
  };

  if (framework === 'all') {
    return {
      'components/Button.tsx': generators.react(),
      'components/Button.vue': generators.vue(),
      'components/Button.svelte': generators.svelte(),
      'components/components.css': generators.vanilla(),
    };
  }

  const filename =
    framework === 'vanilla'
      ? 'components/components.css'
      : `components/Button.${framework === 'react' ? 'tsx' : framework}`;

  return {
    [filename]: generators[framework](),
  };
}
