/**
 * Design Token Generator for Nano UI
 * Generates tokens.json, variables.css, and framework-specific configs
 */

import { ColorPalette, TypographySpec } from '../gemini-client';
import { checkApiKey } from '../tier-manager';

export interface DesignTokens {
  meta: {
    name: string;
    version: string;
    generated: string;
    uniquenessScore: number;
    generator: string;
  };
  colors: ColorPalette;
  typography: {
    display: TypographySpec;
    body: TypographySpec;
    mono?: TypographySpec;
  };
  spacing: {
    unit: number;
    scale: number[];
  };
  radii: {
    none: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
    full: string;
    rationale: string;
  };
  shadows: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
    rationale: string;
  };
  breakpoints: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
    '2xl': string;
  };
}

export interface GeneratorOptions {
  name: string;
  colors: ColorPalette;
  typography: {
    display: TypographySpec;
    body: TypographySpec;
  };
  uniquenessScore: number;
  framework?: 'react' | 'vue' | 'svelte' | 'vanilla' | 'all';
}

/**
 * Generate complete design tokens
 */
export function generateTokens(options: GeneratorOptions): DesignTokens {
  const apiStatus = checkApiKey();

  return {
    meta: {
      name: `${options.name} Design System`,
      version: '1.0.0',
      generated: new Date().toISOString().split('T')[0],
      uniquenessScore: options.uniquenessScore,
      generator: 'nano-ui',
    },
    colors: options.colors,
    typography: {
      display: options.typography.display,
      body: options.typography.body,
    },
    spacing: {
      unit: 4,
      scale: [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64],
    },
    radii: {
      none: '0',
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
      full: '9999px',
      rationale:
        'Mixed radii create visual interest - not everything rounded-xl',
    },
    shadows: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      rationale: 'Subtle shadows that can be tinted with brand colors',
    },
    breakpoints: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
  };
}

/**
 * Generate CSS custom properties
 */
export function generateCSSVariables(tokens: DesignTokens): string {
  const lines: string[] = [
    '/**',
    ` * ${tokens.meta.name}`,
    ` * Generated by Nano UI on ${tokens.meta.generated}`,
    ` * Uniqueness Score: ${tokens.meta.uniquenessScore}/100`,
    ' */',
    '',
    ':root {',
    '  /* Colors */',
  ];

  // Colors
  for (const [name, color] of Object.entries(tokens.colors)) {
    lines.push(`  --color-${name}: ${color.value}; /* ${color.rationale} */`);
  }

  lines.push('', '  /* Typography */');
  lines.push(`  --font-display: '${tokens.typography.display.family}', sans-serif;`);
  lines.push(`  --font-body: '${tokens.typography.body.family}', sans-serif;`);

  lines.push('', '  /* Spacing (multiply by unit) */');
  lines.push(`  --spacing-unit: ${tokens.spacing.unit}px;`);
  tokens.spacing.scale.forEach((s, i) => {
    lines.push(`  --spacing-${i}: ${s * tokens.spacing.unit}px;`);
  });

  lines.push('', '  /* Border Radius */');
  for (const [name, value] of Object.entries(tokens.radii)) {
    if (name !== 'rationale') {
      lines.push(`  --radius-${name}: ${value};`);
    }
  }

  lines.push('', '  /* Shadows */');
  for (const [name, value] of Object.entries(tokens.shadows)) {
    if (name !== 'rationale') {
      lines.push(`  --shadow-${name}: ${value};`);
    }
  }

  lines.push('', '  /* Breakpoints */');
  for (const [name, value] of Object.entries(tokens.breakpoints)) {
    lines.push(`  --breakpoint-${name}: ${value};`);
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate Tailwind config
 */
export function generateTailwindConfig(tokens: DesignTokens): string {
  const colors: Record<string, string> = {};
  for (const [name, color] of Object.entries(tokens.colors)) {
    colors[name] = color.value;
  }

  const config = {
    theme: {
      extend: {
        colors,
        fontFamily: {
          display: [tokens.typography.display.family, 'sans-serif'],
          body: [tokens.typography.body.family, 'sans-serif'],
        },
        borderRadius: {
          none: tokens.radii.none,
          sm: tokens.radii.sm,
          DEFAULT: tokens.radii.md,
          md: tokens.radii.md,
          lg: tokens.radii.lg,
          xl: tokens.radii.xl,
          full: tokens.radii.full,
        },
        boxShadow: {
          sm: tokens.shadows.sm,
          DEFAULT: tokens.shadows.md,
          md: tokens.shadows.md,
          lg: tokens.shadows.lg,
          xl: tokens.shadows.xl,
        },
      },
    },
  };

  return `/**
 * ${tokens.meta.name} - Tailwind Configuration
 * Generated by Nano UI on ${tokens.meta.generated}
 * Uniqueness Score: ${tokens.meta.uniquenessScore}/100
 *
 * Usage: Import this in your tailwind.config.js
 * module.exports = { ...require('./design-system/tailwind.config.js') }
 */

module.exports = ${JSON.stringify(config, null, 2)};
`;
}

/**
 * Generate README documentation
 */
export function generateReadme(tokens: DesignTokens): string {
  return `# ${tokens.meta.name}

Generated by [Nano UI](https://nano-ui.dev) on ${tokens.meta.generated}

## Uniqueness Score: ${tokens.meta.uniquenessScore}/100

This design system was generated with anti-sameness rules to avoid the generic "AI-generated look."

## Files

- \`tokens.json\` - Design tokens in JSON format
- \`variables.css\` - CSS custom properties
- \`tailwind.config.js\` - Tailwind CSS configuration

## Color Palette

| Name | Value | Rationale |
|------|-------|-----------|
${Object.entries(tokens.colors)
  .map(([name, color]) => `| ${name} | \`${color.value}\` | ${color.rationale} |`)
  .join('\n')}

## Typography

### Display Font: ${tokens.typography.display.family}
- Weights: ${tokens.typography.display.weights.join(', ')}
- ${tokens.typography.display.rationale}

### Body Font: ${tokens.typography.body.family}
- Weights: ${tokens.typography.body.weights.join(', ')}
- ${tokens.typography.body.rationale}

## Usage

### CSS Variables
\`\`\`css
@import './design-system/variables.css';

.my-element {
  background-color: var(--color-primary);
  font-family: var(--font-display);
  border-radius: var(--radius-lg);
}
\`\`\`

### Tailwind CSS
\`\`\`js
// tailwind.config.js
module.exports = {
  ...require('./design-system/tailwind.config.js'),
  // your other config
}
\`\`\`

Then use in your HTML/JSX:
\`\`\`html
<div class="bg-primary text-text font-display rounded-lg shadow-md">
  Content
</div>
\`\`\`

## Font Loading

Add these fonts to your project:

\`\`\`html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(tokens.typography.display.family)}:wght@${tokens.typography.display.weights.join(';')}&family=${encodeURIComponent(tokens.typography.body.family)}:wght@${tokens.typography.body.weights.join(';')}&display=swap" rel="stylesheet">
\`\`\`

---

Generated by Nano UI - Design systems that don't look AI-generated.
`;
}

/**
 * Generate all output files
 */
export function generateAllFiles(options: GeneratorOptions): {
  'tokens.json': string;
  'variables.css': string;
  'tailwind.config.js': string;
  'README.md': string;
} {
  const tokens = generateTokens(options);

  return {
    'tokens.json': JSON.stringify(tokens, null, 2),
    'variables.css': generateCSSVariables(tokens),
    'tailwind.config.js': generateTailwindConfig(tokens),
    'README.md': generateReadme(tokens),
  };
}
