/**
 * Visual Generation (Nano Banana) for Nano UI
 * Generates mockups and visual assets using Gemini Imagen API
 */

import { DesignTokens } from './tokens';

export interface VisualOptions {
  tokens: DesignTokens;
  style?: 'mockup' | 'palette' | 'typography' | 'components' | 'all';
  format?: 'png' | 'svg' | 'html';
  size?: { width: number; height: number };
}

export interface VisualResult {
  type: string;
  content: string;
  format: 'png' | 'svg' | 'html' | 'base64';
  filename: string;
}

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';

/**
 * Generate visual assets using Gemini Imagen API
 */
export async function generateVisuals(options: VisualOptions): Promise<VisualResult[]> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY required for visual generation');
  }

  const results: VisualResult[] = [];
  const { tokens, style = 'all' } = options;

  if (style === 'palette' || style === 'all') {
    results.push(generateColorPaletteSVG(tokens));
  }

  if (style === 'typography' || style === 'all') {
    results.push(generateTypographySVG(tokens));
  }

  if (style === 'components' || style === 'all') {
    results.push(generateComponentsSVG(tokens));
  }

  if (style === 'mockup' || style === 'all') {
    results.push(generateMockupHTML(tokens));
  }

  return results;
}

/**
 * Generate SVG color palette swatch
 */
function generateColorPaletteSVG(tokens: DesignTokens): VisualResult {
  const colors = Object.entries(tokens.colors);
  const swatchHeight = 80;
  const swatchWidth = 120;
  const padding = 20;
  const columns = 3;
  const rows = Math.ceil(colors.length / columns);

  const width = columns * swatchWidth + (columns + 1) * padding;
  const height = rows * swatchHeight + (rows + 1) * padding + 60;

  let swatches = '';
  colors.forEach(([name, color], i) => {
    const col = i % columns;
    const row = Math.floor(i / columns);
    const x = padding + col * (swatchWidth + padding);
    const y = 60 + padding + row * (swatchHeight + padding);

    swatches += `
    <g>
      <rect x="${x}" y="${y}" width="${swatchWidth}" height="${swatchHeight - 20}" rx="8" fill="${color.value}"/>
      <text x="${x + swatchWidth / 2}" y="${y + swatchHeight - 5}" text-anchor="middle" font-family="system-ui" font-size="11" fill="#666">${name}</text>
      <text x="${x + swatchWidth / 2}" y="${y + swatchHeight + 8}" text-anchor="middle" font-family="monospace" font-size="9" fill="#999">${color.value}</text>
    </g>`;
  });

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="#fafafa"/>
  <text x="${width / 2}" y="35" text-anchor="middle" font-family="system-ui" font-size="18" font-weight="600" fill="#333">${tokens.meta.name} - Color Palette</text>
  ${swatches}
  <text x="${width / 2}" y="${height - 10}" text-anchor="middle" font-family="system-ui" font-size="10" fill="#999">Generated by Nano UI | Uniqueness Score: ${tokens.meta.uniquenessScore}/100</text>
</svg>`;

  return {
    type: 'palette',
    content: svg,
    format: 'svg',
    filename: 'palette.svg',
  };
}

/**
 * Generate SVG typography specimen
 */
function generateTypographySVG(tokens: DesignTokens): VisualResult {
  const width = 600;
  const height = 400;

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(tokens.typography.display.family)}:wght@${tokens.typography.display.weights.join(';')}&amp;family=${encodeURIComponent(tokens.typography.body.family)}:wght@${tokens.typography.body.weights.join(';')}&amp;display=swap');
    </style>
  </defs>
  <rect width="100%" height="100%" fill="${tokens.colors.background?.value || '#fff'}"/>

  <!-- Title -->
  <text x="30" y="40" font-family="system-ui" font-size="14" fill="#999">TYPOGRAPHY SPECIMEN</text>

  <!-- Display Font -->
  <text x="30" y="100" font-family="'${tokens.typography.display.family}', serif" font-size="48" font-weight="700" fill="${tokens.colors.text?.value || '#333'}">Display Font</text>
  <text x="30" y="130" font-family="'${tokens.typography.display.family}', serif" font-size="24" font-weight="500" fill="${tokens.colors.text?.value || '#333'}">The quick brown fox jumps</text>
  <text x="30" y="155" font-family="system-ui" font-size="12" fill="#999">${tokens.typography.display.family} - ${tokens.typography.display.rationale}</text>

  <!-- Body Font -->
  <text x="30" y="210" font-family="'${tokens.typography.body.family}', sans-serif" font-size="18" font-weight="400" fill="${tokens.colors.text?.value || '#333'}">Body text in ${tokens.typography.body.family}</text>
  <text x="30" y="235" font-family="'${tokens.typography.body.family}', sans-serif" font-size="16" fill="${tokens.colors.text?.value || '#666'}">
    <tspan x="30" dy="0">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</tspan>
    <tspan x="30" dy="24">Sed do eiusmod tempor incididunt ut labore et dolore.</tspan>
  </text>
  <text x="30" y="285" font-family="system-ui" font-size="12" fill="#999">${tokens.typography.body.family} - ${tokens.typography.body.rationale}</text>

  <!-- Scale Preview -->
  <text x="30" y="330" font-family="system-ui" font-size="11" fill="#999">SCALE: xs(12) sm(14) base(16) lg(18) xl(20) 2xl(24) 3xl(30) 4xl(36) 5xl(48)</text>

  <!-- Footer -->
  <text x="${width / 2}" y="${height - 15}" text-anchor="middle" font-family="system-ui" font-size="10" fill="#999">Generated by Nano UI | ${tokens.meta.name}</text>
</svg>`;

  return {
    type: 'typography',
    content: svg,
    format: 'svg',
    filename: 'typography.svg',
  };
}

/**
 * Generate SVG component showcase
 */
function generateComponentsSVG(tokens: DesignTokens): VisualResult {
  const width = 800;
  const height = 500;

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(tokens.typography.display.family)}:wght@${tokens.typography.display.weights.join(';')}&amp;family=${encodeURIComponent(tokens.typography.body.family)}:wght@${tokens.typography.body.weights.join(';')}&amp;display=swap');
    </style>
    <filter id="shadow-md">
      <feDropShadow dx="0" dy="4" stdDeviation="3" flood-opacity="0.1"/>
    </filter>
    <filter id="shadow-lg">
      <feDropShadow dx="0" dy="10" stdDeviation="8" flood-opacity="0.15"/>
    </filter>
  </defs>

  <rect width="100%" height="100%" fill="${tokens.colors.background?.value || '#fafafa'}"/>

  <!-- Title -->
  <text x="40" y="40" font-family="'${tokens.typography.display.family}', serif" font-size="24" font-weight="600" fill="${tokens.colors.text?.value || '#333'}">${tokens.meta.name} - Components</text>

  <!-- Buttons Row -->
  <text x="40" y="90" font-family="system-ui" font-size="12" fill="#999">BUTTONS</text>

  <!-- Primary Button -->
  <rect x="40" y="105" width="120" height="44" rx="${parseInt(tokens.radii.md) || 8}" fill="${tokens.colors.primary?.value || '#3D8F64'}"/>
  <text x="100" y="133" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" font-weight="500" fill="white">Primary</text>

  <!-- Secondary Button -->
  <rect x="180" y="105" width="120" height="44" rx="${parseInt(tokens.radii.md) || 8}" fill="white" stroke="${tokens.colors.primary?.value || '#3D8F64'}" stroke-width="2"/>
  <text x="240" y="133" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" font-weight="500" fill="${tokens.colors.primary?.value || '#3D8F64'}">Secondary</text>

  <!-- Accent Button -->
  <rect x="320" y="105" width="120" height="44" rx="${parseInt(tokens.radii.md) || 8}" fill="${tokens.colors.accent?.value || '#E05A47'}"/>
  <text x="380" y="133" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" font-weight="500" fill="white">Accent CTA</text>

  <!-- Cards Row -->
  <text x="40" y="195" font-family="system-ui" font-size="12" fill="#999">CARDS</text>

  <!-- Card 1 -->
  <rect x="40" y="210" width="220" height="140" rx="${parseInt(tokens.radii.lg) || 16}" fill="${tokens.colors.surface?.value || 'white'}" filter="url(#shadow-md)"/>
  <text x="60" y="250" font-family="'${tokens.typography.display.family}', serif" font-size="18" font-weight="600" fill="${tokens.colors.text?.value || '#333'}">Card Title</text>
  <text x="60" y="280" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" fill="${tokens.colors.text?.value || '#666'}">Some descriptive text</text>
  <text x="60" y="300" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" fill="${tokens.colors.text?.value || '#666'}">goes here nicely.</text>
  <rect x="60" y="320" width="80" height="20" rx="4" fill="${tokens.colors.primary?.value || '#3D8F64'}"/>
  <text x="100" y="334" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="11" fill="white">Action</text>

  <!-- Card 2 -->
  <rect x="280" y="210" width="220" height="140" rx="${parseInt(tokens.radii.lg) || 16}" fill="${tokens.colors.surface?.value || 'white'}" filter="url(#shadow-lg)"/>
  <rect x="280" y="210" width="220" height="8" rx="4" fill="${tokens.colors.accent?.value || '#E05A47'}"/>
  <text x="300" y="260" font-family="'${tokens.typography.display.family}', serif" font-size="18" font-weight="600" fill="${tokens.colors.text?.value || '#333'}">Featured Card</text>
  <text x="300" y="290" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" fill="${tokens.colors.text?.value || '#666'}">With accent highlight</text>

  <!-- Form Elements -->
  <text x="40" y="390" font-family="system-ui" font-size="12" fill="#999">FORM ELEMENTS</text>

  <!-- Input -->
  <rect x="40" y="405" width="200" height="40" rx="6" fill="white" stroke="${tokens.colors.primary?.value || '#ddd'}" stroke-width="1"/>
  <text x="55" y="430" font-family="'${tokens.typography.body.family}', sans-serif" font-size="14" fill="#999">Email address</text>

  <!-- Badges -->
  <rect x="260" y="405" width="60" height="24" rx="12" fill="${tokens.colors.primary?.value || '#3D8F64'}20"/>
  <text x="290" y="421" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="11" font-weight="500" fill="${tokens.colors.primary?.value || '#3D8F64'}">Badge</text>

  <rect x="330" y="405" width="70" height="24" rx="12" fill="${tokens.colors.accent?.value || '#E05A47'}20"/>
  <text x="365" y="421" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="11" font-weight="500" fill="${tokens.colors.accent?.value || '#E05A47'}">Warning</text>

  <rect x="410" y="405" width="70" height="24" rx="12" fill="${tokens.colors.secondary?.value || '#F5A623'}20"/>
  <text x="445" y="421" text-anchor="middle" font-family="'${tokens.typography.body.family}', sans-serif" font-size="11" font-weight="500" fill="${tokens.colors.secondary?.value || '#F5A623'}">New</text>

  <!-- Footer -->
  <text x="${width / 2}" y="${height - 15}" text-anchor="middle" font-family="system-ui" font-size="10" fill="#999">Generated by Nano UI | Uniqueness Score: ${tokens.meta.uniquenessScore}/100</text>
</svg>`;

  return {
    type: 'components',
    content: svg,
    format: 'svg',
    filename: 'components.svg',
  };
}

/**
 * Generate HTML mockup preview
 */
function generateMockupHTML(tokens: DesignTokens): VisualResult {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${tokens.meta.name} - Preview</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(tokens.typography.display.family)}:wght@${tokens.typography.display.weights.join(';')}&family=${encodeURIComponent(tokens.typography.body.family)}:wght@${tokens.typography.body.weights.join(';')}&display=swap" rel="stylesheet">
  <style>
    :root {
      --color-primary: ${tokens.colors.primary?.value || '#3D8F64'};
      --color-secondary: ${tokens.colors.secondary?.value || '#F5A623'};
      --color-accent: ${tokens.colors.accent?.value || '#E05A47'};
      --color-background: ${tokens.colors.background?.value || '#FFFCF9'};
      --color-surface: ${tokens.colors.surface?.value || '#FFFFFF'};
      --color-text: ${tokens.colors.text?.value || '#25221E'};
      --font-display: '${tokens.typography.display.family}', serif;
      --font-body: '${tokens.typography.body.family}', sans-serif;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: var(--font-body);
      background: var(--color-background);
      color: var(--color-text);
      line-height: 1.6;
    }
    .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
    .hero { text-align: center; padding: 4rem 2rem; }
    .hero h1 { font-family: var(--font-display); font-size: 3rem; margin-bottom: 1rem; }
    .hero p { font-size: 1.25rem; opacity: 0.8; margin-bottom: 2rem; }
    .btn {
      display: inline-block; padding: 0.75rem 1.5rem; border-radius: 8px;
      font-weight: 500; text-decoration: none; cursor: pointer; border: none;
      transition: all 0.2s ease;
    }
    .btn-primary { background: var(--color-primary); color: white; }
    .btn-primary:hover { filter: brightness(1.1); transform: translateY(-1px); }
    .btn-accent { background: var(--color-accent); color: white; }
    .btn-accent:hover { filter: brightness(1.1); transform: translateY(-1px); }
    .btn-secondary { background: white; color: var(--color-text); border: 1px solid #ddd; }
    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; margin: 3rem 0; }
    .card { background: var(--color-surface); border-radius: 16px; padding: 1.5rem; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
    .card h3 { font-family: var(--font-display); font-size: 1.25rem; margin-bottom: 0.5rem; }
    .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.8rem; }
    .badge-primary { background: color-mix(in srgb, var(--color-primary) 20%, transparent); color: var(--color-primary); }
    .footer { text-align: center; padding: 2rem; font-size: 0.875rem; opacity: 0.6; }
    .score {
      background: var(--color-accent); color: white;
      padding: 0.5rem 1rem; border-radius: 9999px;
      display: inline-block; font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <header class="hero">
      <span class="score">Uniqueness Score: ${tokens.meta.uniquenessScore}/100</span>
      <h1 style="margin-top: 1.5rem;">${tokens.meta.name}</h1>
      <p>A distinctive design system that doesn't look AI-generated.</p>
      <button class="btn btn-accent" style="margin-right: 0.5rem;">Get Started</button>
      <button class="btn btn-secondary">Learn More</button>
    </header>

    <section class="cards">
      <div class="card">
        <span class="badge badge-primary">Feature</span>
        <h3 style="margin-top: 0.75rem;">Unique Colors</h3>
        <p>Warm, distinctive palette that stands out from generic AI-generated designs.</p>
      </div>
      <div class="card">
        <span class="badge badge-primary">Typography</span>
        <h3 style="margin-top: 0.75rem;">Characterful Fonts</h3>
        <p>${tokens.typography.display.family} + ${tokens.typography.body.family} create memorable brand presence.</p>
      </div>
      <div class="card">
        <span class="badge badge-primary">Components</span>
        <h3 style="margin-top: 0.75rem;">Ready to Use</h3>
        <p>Pre-built components with consistent styling and hover states.</p>
      </div>
    </section>

    <footer class="footer">
      Generated by Nano UI - The Anti-Sameness Engine
    </footer>
  </div>
</body>
</html>`;

  return {
    type: 'mockup',
    content: html,
    format: 'html',
    filename: 'mockup.html',
  };
}

/**
 * Generate Imagen prompt for AI visual generation (premium feature)
 */
export function generateImagenPrompt(tokens: DesignTokens, type: string): string {
  const colorList = Object.entries(tokens.colors)
    .map(([name, color]) => `${name}: ${color.value}`)
    .join(', ');

  const basePrompt = `Professional UI design mockup, clean modern interface`;
  const colorPrompt = `using these exact colors: ${colorList}`;
  const fontPrompt = `with ${tokens.typography.display.family} for headlines and ${tokens.typography.body.family} for body text`;
  const negativePrompt = `NOT generic, NOT blue-purple gradient, NOT corporate template, NOT stock imagery`;

  const typePrompts: Record<string, string> = {
    dashboard: `${basePrompt}, analytics dashboard layout, ${colorPrompt}, ${fontPrompt}, ${negativePrompt}`,
    landing: `${basePrompt}, SaaS landing page hero section, ${colorPrompt}, ${fontPrompt}, ${negativePrompt}`,
    mobile: `${basePrompt}, mobile app interface, ${colorPrompt}, ${fontPrompt}, ${negativePrompt}`,
    components: `${basePrompt}, UI component library showcase, ${colorPrompt}, ${fontPrompt}, ${negativePrompt}`,
  };

  return typePrompts[type] || typePrompts.components;
}
